---
version: '3'

dotenv:
- .vars.public

includes:
  deps: .taskfiles/Taskfile_{{OS}}.yml
  repo: .taskfiles/Taskfile_repo.yml
  ansible: .taskfiles/Taskfile_ansible.yml
  cluster: .taskfiles/Taskfile_cluster.yml
  ci: .taskfiles/Taskfile_ci.yml
  tool: .taskfiles/Taskfile_tool.yml

tasks:
  default:
    cmds:
    - task -l
    silent: true
