---

# Network
- name: network | Set up network
  become: true
  template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
  - { template: interfaces.j2, dest: /etc/network/interfaces.d/ethernet }
  - { template: hosts.j2, dest: /etc/hosts }
  notify:
  - delete dhcp leases

# Hostname
- name: network | Update hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"

- name: network | set /etc/hostname
  become: true
  copy:
    dest: /etc/hostname
    content: "{{ inventory_hostname }}"
  notify:
  - update hostname
