---

- name: packages | disable recommends
  become: true
  copy:
    content: |
      APT::Install-Recommends "false";
      APT::Install-Suggests "false";
      APT::Get::Install-Recommends "false";
      APT::Get::Install-Suggests "false";
    dest: /etc/apt/apt.conf.d/02norecommends

- name: packages | upgrade all packages
  become: true
  apt:
    upgrade: full
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success

- name: packages | install common
  become: true
  apt:
    name: "{{ packages.install }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success
  when:
  - packages.install is defined
  - packages.install is iterable
  - packages.install | length > 0

- name: packages | remove packages
  package_facts:
    manager: auto
  when:
  - packages.remove is defined
  - packages.remove is iterable
  - packages.remove | length > 0

- name: packages | remove packages
  become: true
  apt:
    name: "{{ packages.remove }}"
    state: absent
    autoremove: true
  when:
  - packages.remove is defined
  - packages.remove is iterable
  - packages.remove | length > 0

- name: packages | remove file and directory cruft
  become: true
  file:
    state: absent
    path: "{{ item }}"
  loop:
  - "/home/{{ ansible_user }}/.snap"
  - "/snap"
  - "/var/snap"
  - "/var/lib/snapd"
  - "/var/cache/snapd"
  - "/usr/lib/snapd"
  - "/etc/cloud"
  - "/var/lib/cloud"
  when:
  - packages.remove is defined
  - packages.remove is iterable
  - packages.remove | length > 0
