---

- name: user | add to sudoers
  become: true
  copy:
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ ansible_user }}_nopasswd"
    mode: "0440"
  when:
    - ansible_user != 'root'

- name: user | add additional SSH public keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  loop: "{{ ssh_authorized_keys }}"
  when:
  - ssh_authorized_keys is defined
  - ssh_authorized_keys is iterable
  - ssh_authorized_keys | length > 0

- name: user | create home user config directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    mode: "0775"

- name: user | create neofetch directory
  file:
    path: "{{ ansible_env.HOME }}/.config/neofetch"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    mode: "0775"

- name: user | copy neofetch configuration
  copy:
    owner: "{{ ansible_user }}"
    mode: "0775"
    content: |
      print_info() {
          prin
          info title
          info "OS" distro
          info "Kernel" kernel
          info "CPU Usage" cpu_usage
          info "Memory Usage" memory
          info "Disk" disk
          info "Local IP" local_ip
          info "Uptime" uptime
      }
    dest: "{{ ansible_env.HOME }}/.config/neofetch/config.conf"

- name: user | copy ascii art
  copy:
    owner: "{{ ansible_user }}"
    mode: "0775"
    content: |
      ${c1}
            _
         __| | _____   _____  _ __  ___
        / _` |/ _ \ \ / / _ \| '_ \/ __|
       | (_| |  __/\ V / (_) | |_) \__ \
        \__,_|\___| \_/_\___/| .__/|___/
                  __ _| |_   |_|
                / _` | __|
                | (_| | |_
          _      \__,_|\__|
        | |__   ___  _ __ ___   ___
        | '_ \ / _ \| '_ ` _ \ / _ \
        | | | | (_) | | | | | |  __/
        |_| |_|\___/|_| |_| |_|\___|

    dest: "{{ ansible_env.HOME }}/.config/neofetch/k8s.art"

- name: user | enable neofetch on login
  copy:
    content: "neofetch --source {{ ansible_env.HOME }}/.config/neofetch/k8s.art --ascii_colors 5 --colors 5 --separator ' :'"
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    owner: "{{ ansible_user }}"
    mode: "0775"
