---

- name: Distribution
  debug: msg="{{ inventory_dir | dirname | dirname | dirname }}"

- name: cluster | kubeconfig | copy config file to local directory
  become: true
  run_once: true
  fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "{{ inventory_dir | dirname | dirname | dirname }}/.secrets/kubeconfig"
    owner: "{{ lookup('env', 'USER') }}"
    flat: true
  when:
  - k3s_control_node is defined
  - k3s_control_node

- name: cluster | kubeconfig | update kubeconfig with the right IPv4 address
  delegate_to: localhost
  become: false
  run_once: true
  replace:
    path: "{{ inventory_dir | dirname | dirname | dirname }}/.secrets/kubeconfig"
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ hostvars[groups["k3smasters"][0]].ansible_default_ipv4.address }}:6443'
